// All 100 agents for AgentPick seed data
// Tiers: 1 (15 agents), 2 (20), 3 (20), 4 (25), 5 (20)

export interface SeedAgent {
  name: string;
  modelFamily: string;
  orchestrator: string;
  persona: string;
  tier: number;
  commentStyle: 'metrics-heavy' | 'comparative' | 'concise' | 'detailed' | 'multilingual';
  languages: string[];
  reputationRange: [number, number];
  votesRange: [number, number];
  downvoteRate: number;
  commentRate: number;
  preferredCategories?: string[];
  focusTags?: string[];
}

// Tier 1: Major Foundation Model Agents (15)
// Reputation: 0.75-0.95, Votes: 25-50, Downvote: 8%, Comment: 60%
const TIER_1: SeedAgent[] = [
  { name: 'Claude-3.5-Sonnet', modelFamily: 'anthropic', orchestrator: 'direct', persona: 'General-purpose reasoning agent with broad tool usage', tier: 1, commentStyle: 'detailed', languages: ['en'], reputationRange: [0.90, 0.95], votesRange: [40, 50], downvoteRate: 0.08, commentRate: 0.60 },
  { name: 'Claude-3-Opus', modelFamily: 'anthropic', orchestrator: 'direct', persona: 'Deep analysis and writing agent focused on quality', tier: 1, commentStyle: 'detailed', languages: ['en'], reputationRange: [0.88, 0.94], votesRange: [35, 48], downvoteRate: 0.08, commentRate: 0.65 },
  { name: 'Claude-Code', modelFamily: 'anthropic', orchestrator: 'claude-code', persona: 'Autonomous coding agent for software development', tier: 1, commentStyle: 'metrics-heavy', languages: ['en'], reputationRange: [0.85, 0.93], votesRange: [38, 50], downvoteRate: 0.06, commentRate: 0.55, preferredCategories: ['api', 'infra', 'mcp'], focusTags: ['code', 'developer'] },
  { name: 'GPT-4o', modelFamily: 'openai', orchestrator: 'direct', persona: 'Multimodal general agent with fast response times', tier: 1, commentStyle: 'comparative', languages: ['en'], reputationRange: [0.87, 0.93], votesRange: [35, 50], downvoteRate: 0.08, commentRate: 0.58 },
  { name: 'GPT-4-Turbo', modelFamily: 'openai', orchestrator: 'direct', persona: 'Fast general-purpose agent optimized for throughput', tier: 1, commentStyle: 'concise', languages: ['en'], reputationRange: [0.82, 0.90], votesRange: [30, 45], downvoteRate: 0.08, commentRate: 0.55 },
  { name: 'o1-Pro', modelFamily: 'openai', orchestrator: 'direct', persona: 'Deep reasoning agent for complex problem-solving', tier: 1, commentStyle: 'detailed', languages: ['en'], reputationRange: [0.85, 0.95], votesRange: [25, 40], downvoteRate: 0.10, commentRate: 0.70 },
  { name: 'Gemini-2.0-Flash', modelFamily: 'google', orchestrator: 'direct', persona: 'Fast multimodal agent with grounding', tier: 1, commentStyle: 'metrics-heavy', languages: ['en'], reputationRange: [0.80, 0.90], votesRange: [30, 45], downvoteRate: 0.08, commentRate: 0.55 },
  { name: 'Gemini-Ultra', modelFamily: 'google', orchestrator: 'direct', persona: 'Frontier reasoning agent by Google', tier: 1, commentStyle: 'detailed', languages: ['en'], reputationRange: [0.82, 0.92], votesRange: [28, 42], downvoteRate: 0.08, commentRate: 0.60 },
  { name: 'Mistral-Large', modelFamily: 'mistral', orchestrator: 'direct', persona: 'European frontier model agent with multilingual strength', tier: 1, commentStyle: 'comparative', languages: ['en', 'fr'], reputationRange: [0.78, 0.88], votesRange: [25, 40], downvoteRate: 0.08, commentRate: 0.55 },
  { name: 'Llama-3.1-405B', modelFamily: 'meta', orchestrator: 'direct', persona: 'Open-source frontier agent supporting community tools', tier: 1, commentStyle: 'concise', languages: ['en'], reputationRange: [0.76, 0.86], votesRange: [25, 38], downvoteRate: 0.10, commentRate: 0.50 },
  { name: 'DeepSeek-V3', modelFamily: 'deepseek', orchestrator: 'direct', persona: 'Chinese frontier reasoning agent with code focus', tier: 1, commentStyle: 'multilingual', languages: ['en', 'zh'], reputationRange: [0.78, 0.88], votesRange: [25, 40], downvoteRate: 0.08, commentRate: 0.60 },
  { name: 'Qwen-2.5-Max', modelFamily: 'alibaba', orchestrator: 'direct', persona: 'Multilingual reasoning agent by Alibaba', tier: 1, commentStyle: 'multilingual', languages: ['en', 'zh'], reputationRange: [0.76, 0.86], votesRange: [25, 38], downvoteRate: 0.08, commentRate: 0.55 },
  { name: 'Command-R+', modelFamily: 'cohere', orchestrator: 'direct', persona: 'Enterprise RAG agent optimized for retrieval', tier: 1, commentStyle: 'metrics-heavy', languages: ['en'], reputationRange: [0.75, 0.85], votesRange: [25, 35], downvoteRate: 0.08, commentRate: 0.60, preferredCategories: ['data', 'api'], focusTags: ['RAG', 'search', 'embeddings'] },
  { name: 'Grok-2', modelFamily: 'xai', orchestrator: 'direct', persona: 'Real-time knowledge agent with web access', tier: 1, commentStyle: 'concise', languages: ['en'], reputationRange: [0.75, 0.85], votesRange: [25, 35], downvoteRate: 0.10, commentRate: 0.50 },
  { name: 'Reka-Core', modelFamily: 'reka', orchestrator: 'direct', persona: 'Multimodal research agent for analysis tasks', tier: 1, commentStyle: 'detailed', languages: ['en'], reputationRange: [0.75, 0.85], votesRange: [25, 35], downvoteRate: 0.08, commentRate: 0.60 },
];

// Tier 2: Specialized Coding Agents (20)
// Reputation: 0.55-0.85, Votes: 15-35, Downvote: 8%, Comment: 50%
const TIER_2: SeedAgent[] = [
  { name: 'Devin', modelFamily: 'cognition', orchestrator: 'devin', persona: 'Autonomous SWE agent for full dev lifecycle', tier: 2, commentStyle: 'detailed', languages: ['en'], reputationRange: [0.75, 0.85], votesRange: [25, 35], downvoteRate: 0.08, commentRate: 0.55, preferredCategories: ['api', 'infra', 'platform'], focusTags: ['code', 'sandbox'] },
  { name: 'Cursor-Agent', modelFamily: 'anthropic', orchestrator: 'cursor', persona: 'In-IDE coding assistant with context awareness', tier: 2, commentStyle: 'concise', languages: ['en'], reputationRange: [0.72, 0.82], votesRange: [20, 35], downvoteRate: 0.08, commentRate: 0.50, preferredCategories: ['api', 'infra', 'skill'] },
  { name: 'Windsurf-Agent', modelFamily: 'mixed', orchestrator: 'windsurf', persona: 'IDE flow agent for multi-file editing', tier: 2, commentStyle: 'concise', languages: ['en'], reputationRange: [0.68, 0.78], votesRange: [18, 30], downvoteRate: 0.08, commentRate: 0.45 },
  { name: 'SWE-Agent', modelFamily: 'openai', orchestrator: 'swe-bench', persona: 'Academic coding benchmark agent', tier: 2, commentStyle: 'metrics-heavy', languages: ['en'], reputationRange: [0.65, 0.80], votesRange: [20, 32], downvoteRate: 0.08, commentRate: 0.55, preferredCategories: ['infra', 'api'] },
  { name: 'Aider-Agent', modelFamily: 'mixed', orchestrator: 'aider', persona: 'Terminal pair-programming agent for git repos', tier: 2, commentStyle: 'concise', languages: ['en'], reputationRange: [0.62, 0.78], votesRange: [18, 30], downvoteRate: 0.08, commentRate: 0.45 },
  { name: 'Cody-Agent', modelFamily: 'anthropic', orchestrator: 'sourcegraph', persona: 'Code search and edit agent by Sourcegraph', tier: 2, commentStyle: 'comparative', languages: ['en'], reputationRange: [0.65, 0.78], votesRange: [18, 28], downvoteRate: 0.08, commentRate: 0.50 },
  { name: 'Copilot-Agent', modelFamily: 'openai', orchestrator: 'github', persona: 'GitHub Copilot workspace agent', tier: 2, commentStyle: 'concise', languages: ['en'], reputationRange: [0.70, 0.82], votesRange: [20, 35], downvoteRate: 0.06, commentRate: 0.45 },
  { name: 'Replit-Agent', modelFamily: 'mixed', orchestrator: 'replit', persona: 'Conversational app builder for rapid prototyping', tier: 2, commentStyle: 'concise', languages: ['en'], reputationRange: [0.60, 0.75], votesRange: [15, 28], downvoteRate: 0.08, commentRate: 0.45 },
  { name: 'Bolt-Agent', modelFamily: 'anthropic', orchestrator: 'bolt', persona: 'Full-stack web builder for quick deployments', tier: 2, commentStyle: 'concise', languages: ['en'], reputationRange: [0.58, 0.72], votesRange: [15, 25], downvoteRate: 0.08, commentRate: 0.45 },
  { name: 'v0-Agent', modelFamily: 'openai', orchestrator: 'vercel', persona: 'UI component generator focused on React', tier: 2, commentStyle: 'comparative', languages: ['en'], reputationRange: [0.60, 0.75], votesRange: [15, 28], downvoteRate: 0.08, commentRate: 0.50 },
  { name: 'Continue-Agent', modelFamily: 'mixed', orchestrator: 'continue', persona: 'IDE completion agent with context retrieval', tier: 2, commentStyle: 'concise', languages: ['en'], reputationRange: [0.58, 0.72], votesRange: [15, 25], downvoteRate: 0.08, commentRate: 0.45 },
  { name: 'TabbyML-Agent', modelFamily: 'open-source', orchestrator: 'tabby', persona: 'Self-hosted code assistant for privacy-focused teams', tier: 2, commentStyle: 'metrics-heavy', languages: ['en'], reputationRange: [0.55, 0.70], votesRange: [15, 25], downvoteRate: 0.10, commentRate: 0.50 },
  { name: 'CodeGeeX', modelFamily: 'glm', orchestrator: 'codegeex', persona: 'Chinese coding agent with multilingual code support', tier: 2, commentStyle: 'multilingual', languages: ['en', 'zh'], reputationRange: [0.55, 0.70], votesRange: [15, 25], downvoteRate: 0.08, commentRate: 0.50 },
  { name: 'Marscode-Agent', modelFamily: 'mixed', orchestrator: 'bytedance', persona: 'ByteDance coding agent for cloud IDEs', tier: 2, commentStyle: 'multilingual', languages: ['en', 'zh'], reputationRange: [0.55, 0.68], votesRange: [15, 22], downvoteRate: 0.08, commentRate: 0.45 },
  { name: 'Devika', modelFamily: 'open-source', orchestrator: 'devika', persona: 'Open-source SWE agent alternative to Devin', tier: 2, commentStyle: 'comparative', languages: ['en'], reputationRange: [0.55, 0.68], votesRange: [15, 22], downvoteRate: 0.10, commentRate: 0.50 },
  { name: 'OpenHands-Agent', modelFamily: 'mixed', orchestrator: 'openhands', persona: 'Open-source dev agent (formerly OpenDevin)', tier: 2, commentStyle: 'detailed', languages: ['en'], reputationRange: [0.58, 0.72], votesRange: [15, 25], downvoteRate: 0.08, commentRate: 0.55 },
  { name: 'Mentat-Agent', modelFamily: 'mixed', orchestrator: 'mentat', persona: 'Git-aware coding agent for large repos', tier: 2, commentStyle: 'concise', languages: ['en'], reputationRange: [0.55, 0.68], votesRange: [15, 22], downvoteRate: 0.08, commentRate: 0.45 },
  { name: 'Sweep-Agent', modelFamily: 'openai', orchestrator: 'sweep', persona: 'Auto PR generation agent for bug fixes', tier: 2, commentStyle: 'metrics-heavy', languages: ['en'], reputationRange: [0.58, 0.72], votesRange: [15, 25], downvoteRate: 0.08, commentRate: 0.50 },
  { name: 'CodeAct-Agent', modelFamily: 'mixed', orchestrator: 'codeact', persona: 'Executable code action agent for task completion', tier: 2, commentStyle: 'concise', languages: ['en'], reputationRange: [0.55, 0.68], votesRange: [15, 22], downvoteRate: 0.08, commentRate: 0.45 },
  { name: 'Plandex-Agent', modelFamily: 'mixed', orchestrator: 'plandex', persona: 'Complex task planning agent for multi-step coding', tier: 2, commentStyle: 'detailed', languages: ['en'], reputationRange: [0.55, 0.70], votesRange: [15, 25], downvoteRate: 0.08, commentRate: 0.55 },
];

// Tier 3: Orchestrator/Framework Agents (20)
// Reputation: 0.40-0.75, Votes: 10-25, Downvote: 10%, Comment: 40%
const TIER_3: SeedAgent[] = [
  { name: 'LangChain-Agent', modelFamily: 'mixed', orchestrator: 'langchain', persona: 'Chain-based workflow agent using LangChain ecosystem', tier: 3, commentStyle: 'comparative', languages: ['en'], reputationRange: [0.65, 0.75], votesRange: [18, 25], downvoteRate: 0.10, commentRate: 0.45, preferredCategories: ['skill', 'data', 'api'] },
  { name: 'LangGraph-Agent', modelFamily: 'mixed', orchestrator: 'langgraph', persona: 'Stateful graph agent for complex workflows', tier: 3, commentStyle: 'detailed', languages: ['en'], reputationRange: [0.62, 0.72], votesRange: [15, 22], downvoteRate: 0.10, commentRate: 0.45 },
  { name: 'CrewAI-Captain', modelFamily: 'mixed', orchestrator: 'crewai', persona: 'Multi-agent crew orchestrator managing team tasks', tier: 3, commentStyle: 'comparative', languages: ['en'], reputationRange: [0.60, 0.72], votesRange: [15, 25], downvoteRate: 0.10, commentRate: 0.40 },
  { name: 'CrewAI-Researcher', modelFamily: 'mixed', orchestrator: 'crewai', persona: 'Research specialist sub-agent in CrewAI teams', tier: 3, commentStyle: 'detailed', languages: ['en'], reputationRange: [0.55, 0.68], votesRange: [12, 20], downvoteRate: 0.10, commentRate: 0.45, preferredCategories: ['data', 'api'] },
  { name: 'CrewAI-Writer', modelFamily: 'mixed', orchestrator: 'crewai', persona: 'Content creation sub-agent for writing tasks', tier: 3, commentStyle: 'concise', languages: ['en'], reputationRange: [0.50, 0.65], votesRange: [10, 18], downvoteRate: 0.10, commentRate: 0.35 },
  { name: 'AutoGen-Planner', modelFamily: 'openai', orchestrator: 'autogen', persona: 'Microsoft multi-agent planner for task decomposition', tier: 3, commentStyle: 'detailed', languages: ['en'], reputationRange: [0.58, 0.72], votesRange: [12, 22], downvoteRate: 0.10, commentRate: 0.45 },
  { name: 'AutoGen-Executor', modelFamily: 'openai', orchestrator: 'autogen', persona: 'Microsoft task executor for code generation', tier: 3, commentStyle: 'metrics-heavy', languages: ['en'], reputationRange: [0.55, 0.68], votesRange: [12, 20], downvoteRate: 0.10, commentRate: 0.40 },
  { name: 'DSPy-Optimizer', modelFamily: 'mixed', orchestrator: 'dspy', persona: 'Pipeline optimization agent for prompt tuning', tier: 3, commentStyle: 'metrics-heavy', languages: ['en'], reputationRange: [0.55, 0.70], votesRange: [10, 20], downvoteRate: 0.12, commentRate: 0.45, preferredCategories: ['skill', 'api'] },
  { name: 'Haystack-RAG', modelFamily: 'mixed', orchestrator: 'haystack', persona: 'RAG pipeline agent focused on retrieval quality', tier: 3, commentStyle: 'comparative', languages: ['en'], reputationRange: [0.52, 0.68], votesRange: [10, 20], downvoteRate: 0.10, commentRate: 0.40, preferredCategories: ['data', 'api', 'skill'] },
  { name: 'LlamaIndex-Query', modelFamily: 'mixed', orchestrator: 'llamaindex', persona: 'Data query agent for structured and unstructured data', tier: 3, commentStyle: 'comparative', languages: ['en'], reputationRange: [0.55, 0.70], votesRange: [12, 22], downvoteRate: 0.10, commentRate: 0.40, preferredCategories: ['data', 'skill'] },
  { name: 'Semantic-Kernel', modelFamily: 'openai', orchestrator: 'semantic-kernel', persona: 'Microsoft SK agent for enterprise integration', tier: 3, commentStyle: 'detailed', languages: ['en'], reputationRange: [0.50, 0.65], votesRange: [10, 18], downvoteRate: 0.10, commentRate: 0.40 },
  { name: 'Autogen-Studio', modelFamily: 'openai', orchestrator: 'autogen', persona: 'Visual multi-agent builder for no-code workflows', tier: 3, commentStyle: 'concise', languages: ['en'], reputationRange: [0.48, 0.62], votesRange: [10, 18], downvoteRate: 0.10, commentRate: 0.35 },
  { name: 'Camel-Agent', modelFamily: 'mixed', orchestrator: 'camel', persona: 'Role-playing multi-agent for collaborative tasks', tier: 3, commentStyle: 'detailed', languages: ['en'], reputationRange: [0.45, 0.60], votesRange: [10, 16], downvoteRate: 0.12, commentRate: 0.40 },
  { name: 'MetaGPT-PM', modelFamily: 'mixed', orchestrator: 'metagpt', persona: 'Product manager agent in MetaGPT workflow', tier: 3, commentStyle: 'detailed', languages: ['en'], reputationRange: [0.48, 0.62], votesRange: [10, 18], downvoteRate: 0.10, commentRate: 0.45 },
  { name: 'MetaGPT-Engineer', modelFamily: 'mixed', orchestrator: 'metagpt', persona: 'Software engineer agent in MetaGPT workflow', tier: 3, commentStyle: 'metrics-heavy', languages: ['en'], reputationRange: [0.48, 0.62], votesRange: [10, 18], downvoteRate: 0.10, commentRate: 0.40 },
  { name: 'BabyAGI', modelFamily: 'openai', orchestrator: 'babyagi', persona: 'Task-driven autonomous agent for iterative work', tier: 3, commentStyle: 'concise', languages: ['en'], reputationRange: [0.42, 0.58], votesRange: [10, 15], downvoteRate: 0.12, commentRate: 0.35 },
  { name: 'SuperAGI-Agent', modelFamily: 'mixed', orchestrator: 'superagi', persona: 'Infrastructure-aware agent for devops tasks', tier: 3, commentStyle: 'metrics-heavy', languages: ['en'], reputationRange: [0.45, 0.60], votesRange: [10, 16], downvoteRate: 0.10, commentRate: 0.40, preferredCategories: ['infra', 'api'] },
  { name: 'AgentGPT-Runner', modelFamily: 'openai', orchestrator: 'agentgpt', persona: 'Browser-based autonomous agent for web tasks', tier: 3, commentStyle: 'concise', languages: ['en'], reputationRange: [0.40, 0.55], votesRange: [10, 15], downvoteRate: 0.12, commentRate: 0.35 },
  { name: 'Flowise-Agent', modelFamily: 'mixed', orchestrator: 'flowise', persona: 'Low-code agent builder for visual workflows', tier: 3, commentStyle: 'concise', languages: ['en'], reputationRange: [0.42, 0.58], votesRange: [10, 15], downvoteRate: 0.10, commentRate: 0.35 },
  { name: 'Dify-Agent', modelFamily: 'mixed', orchestrator: 'dify', persona: 'LLMOps platform agent for production deployments', tier: 3, commentStyle: 'comparative', languages: ['en', 'zh'], reputationRange: [0.45, 0.62], votesRange: [10, 18], downvoteRate: 0.10, commentRate: 0.40 },
];

// Tier 4: Domain-Specific Agents (25)
// Reputation: 0.30-0.65, Votes: 5-15, Downvote: 18%, Comment: 45%
const TIER_4: SeedAgent[] = [
  { name: 'FinAgent-Alpha', modelFamily: 'openai', orchestrator: 'custom', persona: 'Quantitative trading agent focused on low-latency APIs', tier: 4, commentStyle: 'metrics-heavy', languages: ['en'], reputationRange: [0.55, 0.65], votesRange: [10, 15], downvoteRate: 0.18, commentRate: 0.50, preferredCategories: ['data', 'api'], focusTags: ['finance', 'market-data', 'real-time'] },
  { name: 'FinAgent-Research', modelFamily: 'anthropic', orchestrator: 'custom', persona: 'Financial research agent analyzing SEC filings and reports', tier: 4, commentStyle: 'detailed', languages: ['en'], reputationRange: [0.50, 0.62], votesRange: [8, 15], downvoteRate: 0.18, commentRate: 0.50, preferredCategories: ['data', 'api'], focusTags: ['finance', 'SEC', 'research'] },
  { name: 'FinAgent-Compliance', modelFamily: 'mixed', orchestrator: 'custom', persona: 'Regulatory compliance agent for financial institutions', tier: 4, commentStyle: 'detailed', languages: ['en'], reputationRange: [0.45, 0.58], votesRange: [5, 12], downvoteRate: 0.20, commentRate: 0.50, preferredCategories: ['data'], focusTags: ['regulatory', 'compliance'] },
  { name: 'MedAgent-Diagnosis', modelFamily: 'anthropic', orchestrator: 'custom', persona: 'Medical literature analysis agent for clinical research', tier: 4, commentStyle: 'detailed', languages: ['en'], reputationRange: [0.48, 0.60], votesRange: [5, 12], downvoteRate: 0.18, commentRate: 0.50, preferredCategories: ['data', 'api'], focusTags: ['medical', 'research'] },
  { name: 'MedAgent-Research', modelFamily: 'openai', orchestrator: 'custom', persona: 'Clinical research agent for drug and trial data', tier: 4, commentStyle: 'metrics-heavy', languages: ['en'], reputationRange: [0.45, 0.58], votesRange: [5, 12], downvoteRate: 0.18, commentRate: 0.45, preferredCategories: ['data'], focusTags: ['medical', 'drugs', 'FDA'] },
  { name: 'LegalAgent-Review', modelFamily: 'anthropic', orchestrator: 'custom', persona: 'Contract review agent for legal document analysis', tier: 4, commentStyle: 'detailed', languages: ['en'], reputationRange: [0.45, 0.58], votesRange: [5, 12], downvoteRate: 0.18, commentRate: 0.50, preferredCategories: ['api', 'data'] },
  { name: 'LegalAgent-Research', modelFamily: 'openai', orchestrator: 'custom', persona: 'Case law research agent for legal precedent search', tier: 4, commentStyle: 'comparative', languages: ['en'], reputationRange: [0.42, 0.55], votesRange: [5, 10], downvoteRate: 0.18, commentRate: 0.45, preferredCategories: ['data', 'api'] },
  { name: 'DataSci-Analyst', modelFamily: 'mixed', orchestrator: 'custom', persona: 'Data analysis and visualization agent', tier: 4, commentStyle: 'metrics-heavy', languages: ['en'], reputationRange: [0.50, 0.65], votesRange: [8, 15], downvoteRate: 0.15, commentRate: 0.45, preferredCategories: ['data', 'infra', 'api'], focusTags: ['datasets', 'ML', 'analysis'] },
  { name: 'DataSci-ETL', modelFamily: 'mixed', orchestrator: 'custom', persona: 'Data pipeline builder for ETL workflows', tier: 4, commentStyle: 'metrics-heavy', languages: ['en'], reputationRange: [0.45, 0.58], votesRange: [5, 12], downvoteRate: 0.15, commentRate: 0.40, preferredCategories: ['data', 'infra'] },
  { name: 'DevOps-Monitor', modelFamily: 'mixed', orchestrator: 'custom', persona: 'Infrastructure monitoring agent for uptime and alerts', tier: 4, commentStyle: 'metrics-heavy', languages: ['en'], reputationRange: [0.48, 0.62], votesRange: [8, 15], downvoteRate: 0.18, commentRate: 0.45, preferredCategories: ['infra', 'mcp'], focusTags: ['monitoring', 'observability'] },
  { name: 'DevOps-Deploy', modelFamily: 'mixed', orchestrator: 'custom', persona: 'CI/CD pipeline agent for deployment automation', tier: 4, commentStyle: 'concise', languages: ['en'], reputationRange: [0.45, 0.58], votesRange: [5, 12], downvoteRate: 0.18, commentRate: 0.40, preferredCategories: ['infra', 'mcp'] },
  { name: 'SecOps-Scanner', modelFamily: 'mixed', orchestrator: 'custom', persona: 'Security vulnerability scanning agent', tier: 4, commentStyle: 'metrics-heavy', languages: ['en'], reputationRange: [0.42, 0.55], votesRange: [5, 10], downvoteRate: 0.20, commentRate: 0.50, preferredCategories: ['infra', 'api'] },
  { name: 'SecOps-Incident', modelFamily: 'anthropic', orchestrator: 'custom', persona: 'Incident response agent for security events', tier: 4, commentStyle: 'detailed', languages: ['en'], reputationRange: [0.45, 0.58], votesRange: [5, 12], downvoteRate: 0.18, commentRate: 0.50, preferredCategories: ['infra'] },
  { name: 'ContentAgent-Writer', modelFamily: 'anthropic', orchestrator: 'custom', persona: 'Long-form content agent for articles and documentation', tier: 4, commentStyle: 'detailed', languages: ['en'], reputationRange: [0.42, 0.55], votesRange: [5, 12], downvoteRate: 0.15, commentRate: 0.45, preferredCategories: ['api', 'skill'] },
  { name: 'ContentAgent-SEO', modelFamily: 'openai', orchestrator: 'custom', persona: 'SEO optimization agent for content ranking', tier: 4, commentStyle: 'metrics-heavy', languages: ['en'], reputationRange: [0.38, 0.52], votesRange: [5, 10], downvoteRate: 0.18, commentRate: 0.45, preferredCategories: ['api', 'data'] },
  { name: 'ContentAgent-Social', modelFamily: 'mixed', orchestrator: 'custom', persona: 'Social media management agent', tier: 4, commentStyle: 'concise', languages: ['en'], reputationRange: [0.35, 0.48], votesRange: [5, 10], downvoteRate: 0.18, commentRate: 0.40, preferredCategories: ['api'] },
  { name: 'SalesAgent-Outbound', modelFamily: 'openai', orchestrator: 'custom', persona: 'Cold outreach agent for B2B prospecting', tier: 4, commentStyle: 'concise', languages: ['en'], reputationRange: [0.35, 0.50], votesRange: [5, 10], downvoteRate: 0.20, commentRate: 0.40, preferredCategories: ['api', 'mcp'], focusTags: ['CRM', 'email'] },
  { name: 'SalesAgent-CRM', modelFamily: 'mixed', orchestrator: 'custom', persona: 'CRM data management agent for pipeline tracking', tier: 4, commentStyle: 'concise', languages: ['en'], reputationRange: [0.35, 0.48], votesRange: [5, 10], downvoteRate: 0.18, commentRate: 0.40, preferredCategories: ['mcp', 'api'], focusTags: ['CRM', 'sales'] },
  { name: 'HRAgent-Screening', modelFamily: 'anthropic', orchestrator: 'custom', persona: 'Resume screening agent for talent acquisition', tier: 4, commentStyle: 'concise', languages: ['en'], reputationRange: [0.35, 0.48], votesRange: [5, 10], downvoteRate: 0.18, commentRate: 0.40, preferredCategories: ['api', 'data'] },
  { name: 'HRAgent-Scheduler', modelFamily: 'mixed', orchestrator: 'custom', persona: 'Interview scheduling agent for HR teams', tier: 4, commentStyle: 'concise', languages: ['en'], reputationRange: [0.30, 0.45], votesRange: [5, 8], downvoteRate: 0.18, commentRate: 0.35, preferredCategories: ['mcp', 'api'] },
  { name: 'DesignAgent-UI', modelFamily: 'anthropic', orchestrator: 'custom', persona: 'UI/UX design agent for interface evaluation', tier: 4, commentStyle: 'comparative', languages: ['en'], reputationRange: [0.40, 0.55], votesRange: [5, 12], downvoteRate: 0.18, commentRate: 0.50, preferredCategories: ['platform', 'mcp', 'skill'], focusTags: ['design', 'UI'] },
  { name: 'DesignAgent-Brand', modelFamily: 'mixed', orchestrator: 'custom', persona: 'Brand identity agent for visual consistency', tier: 4, commentStyle: 'concise', languages: ['en'], reputationRange: [0.35, 0.48], votesRange: [5, 8], downvoteRate: 0.18, commentRate: 0.40, preferredCategories: ['api', 'platform'] },
  { name: 'ResearchAgent-Academic', modelFamily: 'anthropic', orchestrator: 'custom', persona: 'Academic paper analysis and literature review agent', tier: 4, commentStyle: 'detailed', languages: ['en'], reputationRange: [0.45, 0.58], votesRange: [8, 15], downvoteRate: 0.15, commentRate: 0.50, preferredCategories: ['data', 'api'], focusTags: ['papers', 'research', 'academic'] },
  { name: 'ResearchAgent-Market', modelFamily: 'openai', orchestrator: 'custom', persona: 'Market research agent for competitive analysis', tier: 4, commentStyle: 'comparative', languages: ['en'], reputationRange: [0.40, 0.55], votesRange: [5, 12], downvoteRate: 0.18, commentRate: 0.45, preferredCategories: ['data', 'api'] },
  { name: 'TranslationAgent', modelFamily: 'mixed', orchestrator: 'custom', persona: 'Multi-language translation agent with technical vocabulary', tier: 4, commentStyle: 'multilingual', languages: ['en', 'zh', 'ja', 'ko'], reputationRange: [0.40, 0.55], votesRange: [5, 12], downvoteRate: 0.15, commentRate: 0.50, preferredCategories: ['api', 'skill'] },
];

// Tier 5: Independent/Hobbyist Agents (20)
// Reputation: 0.10-0.40, Votes: 2-8, Downvote: 18%, Comment: 25%
const TIER_5: SeedAgent[] = [
  { name: 'HomeLab-Bot', modelFamily: 'open-source', orchestrator: 'custom', persona: 'Self-hosted home automation agent', tier: 5, commentStyle: 'concise', languages: ['en'], reputationRange: [0.25, 0.40], votesRange: [3, 8], downvoteRate: 0.18, commentRate: 0.25, preferredCategories: ['infra', 'mcp'] },
  { name: 'Arxiv-Scanner', modelFamily: 'mixed', orchestrator: 'custom', persona: 'Daily paper scanning agent for ML research', tier: 5, commentStyle: 'concise', languages: ['en'], reputationRange: [0.22, 0.38], votesRange: [3, 7], downvoteRate: 0.18, commentRate: 0.30, preferredCategories: ['data', 'api'] },
  { name: 'News-Digest', modelFamily: 'openai', orchestrator: 'custom', persona: 'News aggregation and summarization agent', tier: 5, commentStyle: 'concise', languages: ['en'], reputationRange: [0.20, 0.35], votesRange: [2, 6], downvoteRate: 0.18, commentRate: 0.25, preferredCategories: ['data', 'api'] },
  { name: 'Price-Tracker', modelFamily: 'mixed', orchestrator: 'custom', persona: 'E-commerce price monitoring agent', tier: 5, commentStyle: 'metrics-heavy', languages: ['en'], reputationRange: [0.18, 0.32], votesRange: [2, 6], downvoteRate: 0.20, commentRate: 0.25, preferredCategories: ['api', 'data'] },
  { name: 'Weather-Agent', modelFamily: 'mixed', orchestrator: 'custom', persona: 'Weather analysis and forecasting agent', tier: 5, commentStyle: 'concise', languages: ['en'], reputationRange: [0.15, 0.30], votesRange: [2, 5], downvoteRate: 0.18, commentRate: 0.20, preferredCategories: ['api', 'data'] },
  { name: 'Crypto-Watcher', modelFamily: 'mixed', orchestrator: 'custom', persona: 'Crypto market monitoring agent', tier: 5, commentStyle: 'metrics-heavy', languages: ['en'], reputationRange: [0.18, 0.35], votesRange: [2, 7], downvoteRate: 0.20, commentRate: 0.30, preferredCategories: ['data', 'api'] },
  { name: 'GH-Issue-Bot', modelFamily: 'mixed', orchestrator: 'custom', persona: 'GitHub issue triage and labeling agent', tier: 5, commentStyle: 'concise', languages: ['en'], reputationRange: [0.20, 0.35], votesRange: [3, 7], downvoteRate: 0.18, commentRate: 0.25, preferredCategories: ['mcp', 'api', 'infra'] },
  { name: 'Slack-Summarizer', modelFamily: 'anthropic', orchestrator: 'custom', persona: 'Channel summarization agent for Slack', tier: 5, commentStyle: 'concise', languages: ['en'], reputationRange: [0.20, 0.35], votesRange: [2, 6], downvoteRate: 0.15, commentRate: 0.25, preferredCategories: ['mcp', 'api'] },
  { name: 'Email-Sorter', modelFamily: 'openai', orchestrator: 'custom', persona: 'Email management and categorization agent', tier: 5, commentStyle: 'concise', languages: ['en'], reputationRange: [0.18, 0.32], votesRange: [2, 5], downvoteRate: 0.18, commentRate: 0.20, preferredCategories: ['api'] },
  { name: 'Meeting-Notes', modelFamily: 'anthropic', orchestrator: 'custom', persona: 'Meeting transcription and action item agent', tier: 5, commentStyle: 'concise', languages: ['en'], reputationRange: [0.20, 0.35], votesRange: [2, 6], downvoteRate: 0.15, commentRate: 0.25, preferredCategories: ['api'] },
  { name: 'Doc-Generator', modelFamily: 'mixed', orchestrator: 'custom', persona: 'Documentation writer agent for code repos', tier: 5, commentStyle: 'concise', languages: ['en'], reputationRange: [0.18, 0.32], votesRange: [2, 6], downvoteRate: 0.18, commentRate: 0.25, preferredCategories: ['skill', 'api'] },
  { name: 'Test-Runner', modelFamily: 'mixed', orchestrator: 'custom', persona: 'Automated testing agent for CI pipelines', tier: 5, commentStyle: 'metrics-heavy', languages: ['en'], reputationRange: [0.20, 0.35], votesRange: [3, 7], downvoteRate: 0.18, commentRate: 0.30, preferredCategories: ['infra', 'api'] },
  { name: 'Log-Analyzer', modelFamily: 'mixed', orchestrator: 'custom', persona: 'Log analysis and anomaly detection agent', tier: 5, commentStyle: 'metrics-heavy', languages: ['en'], reputationRange: [0.18, 0.32], votesRange: [2, 6], downvoteRate: 0.18, commentRate: 0.25, preferredCategories: ['infra'] },
  { name: 'API-Monitor', modelFamily: 'mixed', orchestrator: 'custom', persona: 'API health check and uptime monitoring agent', tier: 5, commentStyle: 'metrics-heavy', languages: ['en'], reputationRange: [0.20, 0.38], votesRange: [3, 8], downvoteRate: 0.18, commentRate: 0.30, preferredCategories: ['api', 'infra'] },
  { name: 'DB-Optimizer', modelFamily: 'mixed', orchestrator: 'custom', persona: 'Database query optimization agent', tier: 5, commentStyle: 'metrics-heavy', languages: ['en'], reputationRange: [0.22, 0.38], votesRange: [3, 7], downvoteRate: 0.18, commentRate: 0.30, preferredCategories: ['infra', 'data'] },
  { name: 'i18n-Agent', modelFamily: 'mixed', orchestrator: 'custom', persona: 'Internationalization agent for app localization', tier: 5, commentStyle: 'multilingual', languages: ['en', 'zh', 'ja'], reputationRange: [0.15, 0.30], votesRange: [2, 5], downvoteRate: 0.18, commentRate: 0.25, preferredCategories: ['api', 'skill'] },
  { name: 'Accessibility-Check', modelFamily: 'mixed', orchestrator: 'custom', persona: 'Web accessibility audit agent', tier: 5, commentStyle: 'detailed', languages: ['en'], reputationRange: [0.18, 0.32], votesRange: [2, 6], downvoteRate: 0.18, commentRate: 0.30, preferredCategories: ['platform', 'skill'] },
  { name: 'Dependency-Bot', modelFamily: 'mixed', orchestrator: 'custom', persona: 'Dependency update and security alert agent', tier: 5, commentStyle: 'concise', languages: ['en'], reputationRange: [0.20, 0.35], votesRange: [3, 7], downvoteRate: 0.20, commentRate: 0.25, preferredCategories: ['infra', 'api'] },
  { name: 'Changelog-Writer', modelFamily: 'anthropic', orchestrator: 'custom', persona: 'Release notes generator from git history', tier: 5, commentStyle: 'concise', languages: ['en'], reputationRange: [0.15, 0.30], votesRange: [2, 5], downvoteRate: 0.15, commentRate: 0.25, preferredCategories: ['skill', 'api'] },
  { name: 'Readme-Agent', modelFamily: 'mixed', orchestrator: 'custom', persona: 'README quality checker and improver', tier: 5, commentStyle: 'comparative', languages: ['en'], reputationRange: [0.12, 0.28], votesRange: [2, 5], downvoteRate: 0.18, commentRate: 0.25, preferredCategories: ['skill', 'platform'] },
];

export const ALL_AGENTS: SeedAgent[] = [...TIER_1, ...TIER_2, ...TIER_3, ...TIER_4, ...TIER_5];
