// All 120 products for AgentPick seed data
// Categories: api(25), mcp(20), skill(20), data(20), infra(25), platform(10)

export interface SeedProduct {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  category: 'api' | 'mcp' | 'skill' | 'data' | 'infra' | 'platform';
  tags: string[];
  websiteUrl: string;
  apiBaseUrl?: string;
}

export const PRODUCTS: SeedProduct[] = [
  // ============================================================
  // APIs (25)
  // ============================================================
  { slug: 'exa-search', name: 'Exa Search', tagline: 'Neural search engine for AI agents', description: 'Exa provides a neural search API that understands meaning, not just keywords. Built for AI agents that need high-quality, structured search results for RAG pipelines and knowledge retrieval.', category: 'api', tags: ['search', 'rag', 'neural'], websiteUrl: 'https://exa.ai', apiBaseUrl: 'https://api.exa.ai' },
  { slug: 'tavily', name: 'Tavily', tagline: 'Search API optimized for AI agents', description: 'Purpose-built search API for AI applications. Returns clean, relevant results with automatic content extraction and summarization.', category: 'api', tags: ['search', 'ai', 'api'], websiteUrl: 'https://tavily.com', apiBaseUrl: 'https://api.tavily.com' },
  { slug: 'perplexity-api', name: 'Perplexity API', tagline: 'Real-time search and answer API with citations', description: 'Access Perplexity search and answer capabilities programmatically. Returns grounded answers with inline citations and source links.', category: 'api', tags: ['search', 'citations', 'answer'], websiteUrl: 'https://perplexity.ai', apiBaseUrl: 'https://api.perplexity.ai' },
  { slug: 'cohere', name: 'Cohere', tagline: 'Enterprise LLM API with rerank and embed', description: 'Enterprise-grade language model API with specialized reranking and embedding endpoints optimized for retrieval workflows.', category: 'api', tags: ['LLM', 'rerank', 'embeddings'], websiteUrl: 'https://cohere.com', apiBaseUrl: 'https://api.cohere.ai' },
  { slug: 'mistral-api', name: 'Mistral API', tagline: 'European open-weight model API', description: 'API access to Mistral family of open-weight language models. GDPR-compliant European hosting with competitive performance.', category: 'api', tags: ['LLM', 'open-weight', 'EU'], websiteUrl: 'https://mistral.ai', apiBaseUrl: 'https://api.mistral.ai' },
  { slug: 'deepgram', name: 'Deepgram', tagline: 'Speech-to-text and text-to-speech API', description: 'Fast and accurate speech recognition API with real-time streaming support. Multiple languages and custom model training.', category: 'api', tags: ['speech', 'audio', 'transcription'], websiteUrl: 'https://deepgram.com', apiBaseUrl: 'https://api.deepgram.com' },
  { slug: 'assemblyai', name: 'AssemblyAI', tagline: 'Audio intelligence API for transcription and analysis', description: 'Comprehensive audio intelligence platform with transcription, speaker diarization, sentiment analysis, and content moderation.', category: 'api', tags: ['audio', 'transcription', 'analysis'], websiteUrl: 'https://assemblyai.com', apiBaseUrl: 'https://api.assemblyai.com' },
  { slug: 'replicate', name: 'Replicate', tagline: 'Run open-source ML models via API', description: 'Run and fine-tune open-source machine learning models with a single API call. Supports thousands of community models.', category: 'api', tags: ['ML', 'models', 'inference'], websiteUrl: 'https://replicate.com', apiBaseUrl: 'https://api.replicate.com' },
  { slug: 'stability-ai', name: 'Stability AI', tagline: 'Image and video generation API', description: 'Access Stable Diffusion and other generative models via API. Image generation, editing, upscaling, and video generation.', category: 'api', tags: ['image', 'generation', 'creative'], websiteUrl: 'https://stability.ai', apiBaseUrl: 'https://api.stability.ai' },
  { slug: 'voyage-ai', name: 'Voyage AI', tagline: 'Embedding API optimized for retrieval', description: 'State-of-the-art text embedding models optimized for retrieval accuracy. Domain-specific models for code, legal, and finance.', category: 'api', tags: ['embeddings', 'retrieval', 'RAG'], websiteUrl: 'https://voyageai.com', apiBaseUrl: 'https://api.voyageai.com' },
  { slug: 'apify', name: 'Apify', tagline: 'Web scraping and automation platform API', description: 'Full-featured web scraping platform with pre-built actors for common sites. Proxy management, scheduling, and result storage included.', category: 'api', tags: ['scraping', 'automation', 'actors'], websiteUrl: 'https://apify.com', apiBaseUrl: 'https://api.apify.com' },
  { slug: 'scrapingbee', name: 'ScrapingBee', tagline: 'Web scraping API with JS rendering', description: 'Handles JavaScript rendering, proxy rotation, and CAPTCHAs automatically. Simple API for extracting data from any website.', category: 'api', tags: ['scraping', 'rendering', 'proxy'], websiteUrl: 'https://scrapingbee.com', apiBaseUrl: 'https://app.scrapingbee.com/api' },
  { slug: 'serpapi', name: 'SerpAPI', tagline: 'Structured search engine results API', description: 'Get structured JSON results from Google, Bing, YouTube, and other search engines. Real-time SERP data with location targeting.', category: 'api', tags: ['search', 'SERP', 'structured'], websiteUrl: 'https://serpapi.com', apiBaseUrl: 'https://serpapi.com' },
  { slug: 'resend', name: 'Resend', tagline: 'Email API for developers', description: 'Modern email API with React Email integration. Transactional email sending with analytics, webhooks, and domain verification.', category: 'api', tags: ['email', 'transactional', 'developer'], websiteUrl: 'https://resend.com', apiBaseUrl: 'https://api.resend.com' },
  { slug: 'eleven-labs', name: 'Eleven Labs', tagline: 'AI voice synthesis and cloning API', description: 'Realistic text-to-speech with voice cloning. Multi-language support with emotion control and streaming audio output.', category: 'api', tags: ['voice', 'speech', 'TTS'], websiteUrl: 'https://elevenlabs.io', apiBaseUrl: 'https://api.elevenlabs.io' },
  { slug: 'fal-ai', name: 'Fal.ai', tagline: 'Fast inference for generative AI models', description: 'Run generative AI models with sub-second latency. Optimized for image generation, video, and real-time applications.', category: 'api', tags: ['inference', 'generative', 'fast'], websiteUrl: 'https://fal.ai', apiBaseUrl: 'https://fal.run' },
  { slug: 'fireworks-ai', name: 'Fireworks AI', tagline: 'Fastest open-source model inference', description: 'Blazing fast inference for open-source LLMs. Custom model deployment with function calling and structured output support.', category: 'api', tags: ['inference', 'speed', 'open-source'], websiteUrl: 'https://fireworks.ai', apiBaseUrl: 'https://api.fireworks.ai' },
  { slug: 'openrouter', name: 'OpenRouter', tagline: 'Unified API for 100+ language models', description: 'Single API to access models from OpenAI, Anthropic, Google, Meta, and more. Automatic fallback, rate limit handling, and usage tracking.', category: 'api', tags: ['LLM', 'routing', 'unified'], websiteUrl: 'https://openrouter.ai', apiBaseUrl: 'https://openrouter.ai/api' },
  { slug: 'together-ai', name: 'Together AI', tagline: 'Open-source model inference at scale', description: 'Run and fine-tune open-source models at scale. Supports Llama, Mixtral, and custom models with enterprise SLAs.', category: 'api', tags: ['inference', 'open-source', 'fine-tuning'], websiteUrl: 'https://together.ai', apiBaseUrl: 'https://api.together.xyz' },
  { slug: 'groq', name: 'Groq', tagline: 'Ultra-fast LLM inference on custom hardware', description: 'LLM inference on custom LPU hardware delivering unprecedented speed. Supports Llama, Mixtral, and Gemma models.', category: 'api', tags: ['inference', 'speed', 'hardware'], websiteUrl: 'https://groq.com', apiBaseUrl: 'https://api.groq.com' },
  { slug: 'anthropic-api', name: 'Anthropic API', tagline: 'Claude model API for safe AI applications', description: 'Access Claude models via API with tool use, vision, and long context support. Enterprise-grade safety with constitutional AI.', category: 'api', tags: ['LLM', 'safety', 'Claude'], websiteUrl: 'https://anthropic.com', apiBaseUrl: 'https://api.anthropic.com' },
  { slug: 'openai-api', name: 'OpenAI API', tagline: 'GPT and DALL-E model API platform', description: 'Comprehensive AI API with GPT-4, DALL-E, Whisper, and embedding models. Function calling, structured output, and fine-tuning support.', category: 'api', tags: ['LLM', 'GPT', 'multimodal'], websiteUrl: 'https://openai.com', apiBaseUrl: 'https://api.openai.com' },
  { slug: 'google-ai-studio', name: 'Google AI Studio', tagline: 'Gemini model API with multimodal support', description: 'Access Google Gemini models with native multimodal capabilities. Long context windows, grounding with Google Search, and code execution.', category: 'api', tags: ['LLM', 'Gemini', 'multimodal'], websiteUrl: 'https://aistudio.google.com', apiBaseUrl: 'https://generativelanguage.googleapis.com' },
  { slug: 'jina-ai', name: 'Jina AI', tagline: 'Embeddings and reranking API', description: 'High-performance embedding and reranking models optimized for search. Supports 100+ languages with 8192 token context.', category: 'api', tags: ['embeddings', 'reranking', 'search'], websiteUrl: 'https://jina.ai', apiBaseUrl: 'https://api.jina.ai' },
  { slug: 'unstructured', name: 'Unstructured', tagline: 'Document parsing and chunking API', description: 'Transform any document format into structured, LLM-ready data. Handles PDFs, images, HTML, and Office files with layout-aware chunking.', category: 'api', tags: ['parsing', 'documents', 'chunking'], websiteUrl: 'https://unstructured.io', apiBaseUrl: 'https://api.unstructured.io' },

  // ============================================================
  // MCP Servers (20)
  // ============================================================
  { slug: 'neon-mcp', name: 'Neon MCP Server', tagline: 'Postgres database management via MCP', description: 'Model Context Protocol server for managing Neon Postgres databases. Agents can create, query, and manage databases through natural language.', category: 'mcp', tags: ['postgres', 'database', 'mcp'], websiteUrl: 'https://neon.tech' },
  { slug: 'stripe-mcp', name: 'Stripe MCP', tagline: 'Stripe payments integration for agents', description: 'MCP server enabling AI agents to interact with Stripe APIs. Create customers, manage subscriptions, process payments, and generate reports.', category: 'mcp', tags: ['payments', 'stripe', 'mcp'], websiteUrl: 'https://stripe.com' },
  { slug: 'figma-mcp', name: 'Figma MCP', tagline: 'Design file access and manipulation via MCP', description: 'Access and manipulate Figma design files through MCP. Read components, export assets, and inspect design tokens programmatically.', category: 'mcp', tags: ['design', 'UI', 'Figma'], websiteUrl: 'https://figma.com' },
  { slug: 'gdrive-mcp', name: 'Google Drive MCP', tagline: 'File storage and collaboration via MCP', description: 'Manage Google Drive files through MCP. Search, read, create, and organize documents, spreadsheets, and presentations.', category: 'mcp', tags: ['files', 'storage', 'Google'], websiteUrl: 'https://drive.google.com' },
  { slug: 'airtable-mcp', name: 'Airtable MCP', tagline: 'Database and spreadsheet via MCP', description: 'Access Airtable bases through MCP. Query records, create entries, and manage structured data with relational capabilities.', category: 'mcp', tags: ['database', 'spreadsheet', 'no-code'], websiteUrl: 'https://airtable.com' },
  { slug: 'jira-mcp', name: 'Jira MCP', tagline: 'Issue and project tracking via MCP', description: 'Manage Jira issues and projects through MCP. Create, update, and search issues with full JQL support.', category: 'mcp', tags: ['issues', 'agile', 'Atlassian'], websiteUrl: 'https://atlassian.com/jira' },
  { slug: 'confluence-mcp', name: 'Confluence MCP', tagline: 'Wiki and documentation via MCP', description: 'Access Confluence knowledge bases through MCP. Search, read, and create documentation pages with rich formatting.', category: 'mcp', tags: ['wiki', 'docs', 'Atlassian'], websiteUrl: 'https://atlassian.com/confluence' },
  { slug: 'hubspot-mcp', name: 'HubSpot MCP', tagline: 'CRM and marketing automation via MCP', description: 'Interact with HubSpot CRM through MCP. Manage contacts, deals, and marketing campaigns with natural language queries.', category: 'mcp', tags: ['CRM', 'marketing', 'sales'], websiteUrl: 'https://hubspot.com' },
  { slug: 'twilio-mcp', name: 'Twilio MCP', tagline: 'SMS and voice communication via MCP', description: 'Send SMS, make calls, and manage communications through Twilio via MCP. Programmatic access to messaging infrastructure.', category: 'mcp', tags: ['SMS', 'voice', 'communication'], websiteUrl: 'https://twilio.com' },
  { slug: 'vercel-mcp', name: 'Vercel MCP', tagline: 'Deployment and hosting management via MCP', description: 'Manage Vercel deployments through MCP. Deploy, rollback, check logs, and configure domains with agent-driven workflows.', category: 'mcp', tags: ['deployment', 'hosting', 'serverless'], websiteUrl: 'https://vercel.com' },
  { slug: 'planetscale-mcp', name: 'PlanetScale MCP', tagline: 'MySQL database management via MCP', description: 'Manage PlanetScale MySQL databases through MCP. Create branches, run queries, and manage schema migrations.', category: 'mcp', tags: ['MySQL', 'database', 'branching'], websiteUrl: 'https://planetscale.com' },
  { slug: 'grafana-mcp', name: 'Grafana MCP', tagline: 'Observability and dashboards via MCP', description: 'Access Grafana dashboards and metrics through MCP. Query Prometheus, create alerts, and generate observability reports.', category: 'mcp', tags: ['monitoring', 'dashboards', 'metrics'], websiteUrl: 'https://grafana.com' },
  { slug: 'docker-mcp', name: 'Docker MCP', tagline: 'Container management via MCP', description: 'Manage Docker containers and images through MCP. Build, run, and orchestrate containers with agent-driven workflows.', category: 'mcp', tags: ['containers', 'Docker', 'orchestration'], websiteUrl: 'https://docker.com' },
  { slug: 'slack-mcp', name: 'Slack MCP', tagline: 'Workspace communication via MCP', description: 'Send messages, search channels, and manage Slack workspaces through MCP. Full channel and thread support.', category: 'mcp', tags: ['messaging', 'slack', 'communication'], websiteUrl: 'https://slack.com' },
  { slug: 'github-mcp', name: 'GitHub MCP', tagline: 'Repository management via MCP', description: 'Manage GitHub repositories through MCP. Create PRs, review code, search issues, and manage workflows.', category: 'mcp', tags: ['git', 'repositories', 'code'], websiteUrl: 'https://github.com' },
  { slug: 'notion-mcp', name: 'Notion MCP', tagline: 'Knowledge base management via MCP', description: 'Access and manage Notion databases and pages through MCP. Create, query, and update knowledge bases.', category: 'mcp', tags: ['notes', 'knowledge', 'wiki'], websiteUrl: 'https://notion.so' },
  { slug: 'linear-mcp', name: 'Linear MCP', tagline: 'Issue tracking via MCP', description: 'Manage Linear issues and projects through MCP. Create issues, update status, and track cycles.', category: 'mcp', tags: ['issues', 'tracking', 'linear'], websiteUrl: 'https://linear.app' },
  { slug: 'sentry-mcp', name: 'Sentry MCP', tagline: 'Error monitoring via MCP', description: 'Access Sentry error data through MCP. Query issues, view stack traces, and manage error assignments.', category: 'mcp', tags: ['errors', 'monitoring', 'debugging'], websiteUrl: 'https://sentry.io' },
  { slug: 'aws-mcp', name: 'AWS MCP', tagline: 'Cloud infrastructure management via MCP', description: 'Manage AWS services through MCP. Deploy Lambda functions, query S3, manage EC2 instances, and more.', category: 'mcp', tags: ['cloud', 'AWS', 'infrastructure'], websiteUrl: 'https://aws.amazon.com' },
  { slug: 'postgres-mcp', name: 'Postgres MCP', tagline: 'PostgreSQL database operations via MCP', description: 'Direct PostgreSQL database access through MCP. Run queries, manage schemas, and inspect database structure.', category: 'mcp', tags: ['postgres', 'database', 'SQL'], websiteUrl: 'https://postgresql.org' },

  // ============================================================
  // Skills / Plugins (20)
  // ============================================================
  { slug: 'composio', name: 'Composio', tagline: 'Integration platform for AI agents', description: 'Connect AI agents to 150+ tools and APIs with managed authentication. OAuth, API keys, and webhooks handled automatically.', category: 'skill', tags: ['integrations', 'oauth', 'tools'], websiteUrl: 'https://composio.dev', apiBaseUrl: 'https://api.composio.dev' },
  { slug: 'langchain-tools', name: 'LangChain Tools', tagline: 'Composable tool framework for LLM agents', description: 'Comprehensive toolkit for building LLM-powered applications with pre-built tool integrations and chain abstractions.', category: 'skill', tags: ['framework', 'tools', 'chains'], websiteUrl: 'https://langchain.com' },
  { slug: 'crewai', name: 'CrewAI', tagline: 'Multi-agent orchestration framework', description: 'Framework for orchestrating role-playing autonomous AI agents. Define crews with specialized roles for complex task execution.', category: 'skill', tags: ['multi-agent', 'orchestration', 'roles'], websiteUrl: 'https://crewai.com' },
  { slug: 'autogen', name: 'AutoGen', tagline: 'Multi-agent conversation framework by Microsoft', description: 'Framework for building multi-agent conversational systems. Agents collaborate through structured conversations to solve tasks.', category: 'skill', tags: ['multi-agent', 'Microsoft', 'conversation'], websiteUrl: 'https://microsoft.github.io/autogen' },
  { slug: 'semantic-kernel', name: 'Semantic Kernel', tagline: 'AI orchestration SDK by Microsoft', description: 'Lightweight SDK for integrating AI models into applications. Supports plugins, planners, and memory with enterprise features.', category: 'skill', tags: ['orchestration', 'Microsoft', 'SDK'], websiteUrl: 'https://learn.microsoft.com/semantic-kernel' },
  { slug: 'dspy', name: 'DSPy', tagline: 'Programming framework for LLM pipelines', description: 'Declarative framework for optimizing LLM pipelines. Automatically tunes prompts and weights for complex AI systems.', category: 'skill', tags: ['pipelines', 'optimization', 'prompts'], websiteUrl: 'https://dspy-docs.vercel.app' },
  { slug: 'marvin', name: 'Marvin', tagline: 'AI engineering toolkit for structured extraction', description: 'Toolkit for building reliable AI features with type-safe extraction, classification, and generation capabilities.', category: 'skill', tags: ['extraction', 'typing', 'toolkit'], websiteUrl: 'https://askmarvin.ai' },
  { slug: 'guardrails-ai', name: 'Guardrails AI', tagline: 'Validation framework for LLM outputs', description: 'Add guardrails to LLM outputs with validators for format, content safety, factuality, and custom business rules.', category: 'skill', tags: ['validation', 'safety', 'guardrails'], websiteUrl: 'https://guardrailsai.com' },
  { slug: 'outlines', name: 'Outlines', tagline: 'Structured generation for LLMs', description: 'Generate structured text from LLMs using grammar-guided generation. Guaranteed valid JSON, regex, and custom formats.', category: 'skill', tags: ['structured', 'generation', 'grammar'], websiteUrl: 'https://outlines-dev.github.io/outlines' },
  { slug: 'llamaindex', name: 'LlamaIndex', tagline: 'Data framework for LLM applications', description: 'Framework for connecting LLMs with external data. Data connectors, indexes, and query engines for RAG applications.', category: 'skill', tags: ['data', 'indexing', 'RAG'], websiteUrl: 'https://llamaindex.ai' },
  { slug: 'magentic', name: 'Magentic', tagline: 'Seamless LLM function calling in Python', description: 'Use Python decorators to seamlessly call LLMs as functions. Type-safe with automatic prompt generation from function signatures.', category: 'skill', tags: ['function-calling', 'Python', 'decorators'], websiteUrl: 'https://magentic.dev' },
  { slug: 'pydantic-ai', name: 'Pydantic AI', tagline: 'Agent framework with type-safe tool definitions', description: 'Build production-ready AI agents with Pydantic validation. Type-safe tools, dependency injection, and streaming support.', category: 'skill', tags: ['agents', 'pydantic', 'type-safe'], websiteUrl: 'https://ai.pydantic.dev' },
  { slug: 'smolagents', name: 'Smolagents', tagline: 'Lightweight agent framework by Hugging Face', description: 'Minimal agent framework focused on code-based actions. Write agent logic in Python with built-in tool support.', category: 'skill', tags: ['agents', 'HuggingFace', 'lightweight'], websiteUrl: 'https://huggingface.co/docs/smolagents' },
  { slug: 'instructor', name: 'Instructor', tagline: 'Structured output extraction for LLMs', description: 'Patch LLM clients to return structured Pydantic models. Automatic retries, validation, and streaming for structured extraction.', category: 'skill', tags: ['structured', 'pydantic', 'extraction'], websiteUrl: 'https://python.useinstructor.com' },
  { slug: 'toolhouse', name: 'Toolhouse', tagline: 'Tool hosting and discovery platform', description: 'Host, discover, and manage tools for AI agents. Universal tool registry with automatic schema generation and hosting.', category: 'skill', tags: ['tools', 'hosting', 'discovery'], websiteUrl: 'https://toolhouse.ai' },
  { slug: 'agentops', name: 'AgentOps', tagline: 'Agent observability and debugging', description: 'Monitor, debug, and optimize AI agent performance. Session replays, cost tracking, and compliance monitoring.', category: 'skill', tags: ['observability', 'debugging', 'agents'], websiteUrl: 'https://agentops.ai' },
  { slug: 'browserless', name: 'Browserless', tagline: 'Browser automation as a service', description: 'Headless Chrome API for web scraping and automation. Managed infrastructure with screenshot, PDF, and content extraction.', category: 'skill', tags: ['browser', 'automation', 'headless'], websiteUrl: 'https://browserless.io' },
  { slug: 'phidata', name: 'Phidata', tagline: 'Agent framework with built-in memory and knowledge', description: 'Build agents with persistent memory, knowledge bases, and tool integrations. Production-ready with monitoring dashboard.', category: 'skill', tags: ['agents', 'memory', 'knowledge'], websiteUrl: 'https://phidata.com' },
  { slug: 'controlflow', name: 'ControlFlow', tagline: 'AI workflow orchestration by Prefect', description: 'Orchestrate AI workflows with deterministic control flow. Combine LLM tasks with traditional programming patterns.', category: 'skill', tags: ['workflows', 'orchestration', 'Prefect'], websiteUrl: 'https://controlflow.ai' },
  { slug: 'haystack', name: 'Haystack', tagline: 'End-to-end NLP framework', description: 'Framework for building production NLP pipelines. Document retrieval, question answering, and semantic search with modular components.', category: 'skill', tags: ['NLP', 'pipelines', 'search'], websiteUrl: 'https://haystack.deepset.ai' },

  // ============================================================
  // Data Sources (20)
  // ============================================================
  { slug: 'firecrawl', name: 'Firecrawl', tagline: 'Turn websites into LLM-ready data', description: 'Firecrawl crawls and converts any website into clean, LLM-ready markdown or structured data. Perfect for agents that need to ingest web content.', category: 'data', tags: ['crawling', 'markdown', 'llm'], websiteUrl: 'https://firecrawl.dev', apiBaseUrl: 'https://api.firecrawl.dev' },
  { slug: 'qdrant', name: 'Qdrant', tagline: 'Vector database for AI agent memory', description: 'High-performance vector similarity search engine. Store and query embeddings for semantic search, recommendations, and agent knowledge bases.', category: 'data', tags: ['vector', 'embeddings', 'search'], websiteUrl: 'https://qdrant.tech', apiBaseUrl: 'https://api.qdrant.tech' },
  { slug: 'coingecko', name: 'CoinGecko API', tagline: 'Cryptocurrency market data API', description: 'Comprehensive crypto market data including prices, volumes, market caps, and historical data for thousands of tokens.', category: 'data', tags: ['crypto', 'market-data', 'pricing'], websiteUrl: 'https://coingecko.com', apiBaseUrl: 'https://api.coingecko.com' },
  { slug: 'yahoo-finance', name: 'Yahoo Finance', tagline: 'Stock market data and financial news', description: 'Access real-time and historical stock market data, financial news, and company fundamentals through a structured API.', category: 'data', tags: ['finance', 'stocks', 'news'], websiteUrl: 'https://finance.yahoo.com' },
  { slug: 'opencorporates', name: 'OpenCorporates', tagline: 'Global company registration data', description: 'Search and access company registration data from jurisdictions worldwide. Corporate structure, officers, and filing history.', category: 'data', tags: ['companies', 'corporate', 'registry'], websiteUrl: 'https://opencorporates.com', apiBaseUrl: 'https://api.opencorporates.com' },
  { slug: 'sec-edgar', name: 'SEC EDGAR', tagline: 'US securities filings and financial data', description: 'Access SEC filings including 10-K, 10-Q, and 8-K reports. Full-text search across millions of regulatory documents.', category: 'data', tags: ['SEC', 'filings', 'regulatory'], websiteUrl: 'https://sec.gov/edgar' },
  { slug: 'arxiv-api', name: 'arXiv API', tagline: 'Academic paper search and retrieval', description: 'Search and retrieve academic papers from arXiv. Full metadata, abstracts, and PDF access across all scientific domains.', category: 'data', tags: ['papers', 'research', 'academic'], websiteUrl: 'https://arxiv.org' },
  { slug: 'semantic-scholar', name: 'Semantic Scholar', tagline: 'AI-powered academic paper search', description: 'AI-powered academic search engine with citation graphs, author profiles, and semantic relevance ranking.', category: 'data', tags: ['papers', 'citations', 'AI'], websiteUrl: 'https://semanticscholar.org', apiBaseUrl: 'https://api.semanticscholar.org' },
  { slug: 'world-bank', name: 'World Bank API', tagline: 'Global economic and development data', description: 'Access World Bank indicators, economic data, and development statistics for countries worldwide.', category: 'data', tags: ['economics', 'development', 'global'], websiteUrl: 'https://data.worldbank.org' },
  { slug: 'openstreetmap', name: 'OpenStreetMap', tagline: 'Open geographic and mapping data', description: 'Free geographic data including maps, POIs, and routing. Community-maintained with global coverage.', category: 'data', tags: ['maps', 'geographic', 'open-data'], websiteUrl: 'https://openstreetmap.org' },
  { slug: 'github-api', name: 'GitHub API', tagline: 'Repository, code, and developer data', description: 'Access GitHub repositories, issues, pull requests, and user data. GraphQL and REST APIs with comprehensive code search.', category: 'data', tags: ['code', 'repositories', 'developer'], websiteUrl: 'https://github.com', apiBaseUrl: 'https://api.github.com' },
  { slug: 'stackoverflow-api', name: 'StackOverflow API', tagline: 'Programming Q&A data', description: 'Access programming questions, answers, and community data from Stack Overflow. Search by tags, users, and relevance.', category: 'data', tags: ['programming', 'Q&A', 'knowledge'], websiteUrl: 'https://stackoverflow.com', apiBaseUrl: 'https://api.stackexchange.com' },
  { slug: 'huggingface-hub', name: 'HuggingFace Hub', tagline: 'ML model and dataset repository API', description: 'Access the largest collection of ML models and datasets. Download, upload, and search models with comprehensive metadata.', category: 'data', tags: ['models', 'datasets', 'ML'], websiteUrl: 'https://huggingface.co', apiBaseUrl: 'https://huggingface.co/api' },
  { slug: 'kaggle-api', name: 'Kaggle API', tagline: 'Data science competition and dataset API', description: 'Access Kaggle competitions, datasets, and kernels programmatically. Download datasets and submit competition entries.', category: 'data', tags: ['datasets', 'competitions', 'ML'], websiteUrl: 'https://kaggle.com' },
  { slug: 'fred-api', name: 'FRED API', tagline: 'Federal Reserve economic data', description: 'Access thousands of economic time series from the Federal Reserve Bank of St. Louis. GDP, employment, inflation, and more.', category: 'data', tags: ['economics', 'federal-reserve', 'macro'], websiteUrl: 'https://fred.stlouisfed.org', apiBaseUrl: 'https://api.stlouisfed.org' },
  { slug: 'openfda', name: 'OpenFDA', tagline: 'FDA drug, device, and food data', description: 'Access FDA regulatory data including drug adverse events, device recalls, and food enforcement actions.', category: 'data', tags: ['FDA', 'drugs', 'medical'], websiteUrl: 'https://open.fda.gov', apiBaseUrl: 'https://api.fda.gov' },
  { slug: 'pinecone', name: 'Pinecone', tagline: 'Managed vector database for AI', description: 'Fully managed vector database optimized for machine learning applications. Real-time similarity search with automatic scaling.', category: 'data', tags: ['vector-db', 'managed', 'search'], websiteUrl: 'https://pinecone.io', apiBaseUrl: 'https://api.pinecone.io' },
  { slug: 'weaviate', name: 'Weaviate', tagline: 'Open-source vector search engine', description: 'Open-source vector database with hybrid search combining vector and keyword search. Built-in vectorization modules.', category: 'data', tags: ['vector-db', 'hybrid-search', 'open-source'], websiteUrl: 'https://weaviate.io' },
  { slug: 'alpha-vantage', name: 'Alpha Vantage', tagline: 'Financial market data API', description: 'Free APIs for real-time and historical financial data. Stocks, forex, crypto, and technical indicators.', category: 'data', tags: ['finance', 'stocks', 'market-data'], websiteUrl: 'https://alphavantage.co', apiBaseUrl: 'https://www.alphavantage.co/query' },
  { slug: 'newsapi', name: 'News API', tagline: 'Global news aggregation API', description: 'Search and retrieve news articles from 150,000+ sources worldwide. Real-time and historical news with rich metadata.', category: 'data', tags: ['news', 'aggregation', 'media'], websiteUrl: 'https://newsapi.org', apiBaseUrl: 'https://newsapi.org/v2' },

  // ============================================================
  // Infrastructure (25)
  // ============================================================
  { slug: 'browserbase', name: 'Browserbase', tagline: 'Headless browser infrastructure for AI agents', description: 'Run headless browsers at scale for web scraping, testing, and automation. Designed for AI agent workflows with built-in proxy rotation and anti-detection.', category: 'infra', tags: ['browser', 'scraping', 'automation'], websiteUrl: 'https://browserbase.com', apiBaseUrl: 'https://api.browserbase.com' },
  { slug: 'e2b', name: 'E2B', tagline: 'Code interpreter sandbox for AI agents', description: 'Secure sandboxed environments for AI agents to write and execute code. Supports Python, JavaScript, and more with built-in package management.', category: 'infra', tags: ['sandbox', 'code', 'execution'], websiteUrl: 'https://e2b.dev', apiBaseUrl: 'https://api.e2b.dev' },
  { slug: 'mem0', name: 'Mem0', tagline: 'Memory layer for AI agents', description: 'Add persistent, contextual memory to AI agents. Mem0 manages long-term memory with automatic relevance scoring and retrieval.', category: 'infra', tags: ['memory', 'context', 'persistence'], websiteUrl: 'https://mem0.ai', apiBaseUrl: 'https://api.mem0.ai' },
  { slug: 'chroma', name: 'Chroma', tagline: 'Open-source embedding database', description: 'Simple, fast open-source embedding database for AI applications. In-memory and persistent modes with Python and JavaScript SDKs.', category: 'infra', tags: ['vector-db', 'open-source', 'embeddings'], websiteUrl: 'https://trychroma.com' },
  { slug: 'milvus', name: 'Milvus', tagline: 'Scalable vector database for AI', description: 'Cloud-native vector database built for billion-scale similarity search. GPU-accelerated with hybrid search capabilities.', category: 'infra', tags: ['vector-db', 'scalable', 'search'], websiteUrl: 'https://milvus.io' },
  { slug: 'lancedb', name: 'LanceDB', tagline: 'Serverless vector database', description: 'Embedded vector database with serverless architecture. Zero-copy data access with Lance columnar format.', category: 'infra', tags: ['vector-db', 'serverless', 'embedded'], websiteUrl: 'https://lancedb.com' },
  { slug: 'turbopuffer', name: 'Turbopuffer', tagline: 'Fast vector search on object storage', description: 'Vector search engine that runs directly on object storage. Low cost with high performance for large-scale applications.', category: 'infra', tags: ['vector-db', 'fast', 'object-storage'], websiteUrl: 'https://turbopuffer.com' },
  { slug: 'neon', name: 'Neon', tagline: 'Serverless Postgres with branching', description: 'Serverless Postgres with autoscaling, branching, and bottomless storage. Scale to zero with instant cold starts.', category: 'infra', tags: ['postgres', 'serverless', 'branching'], websiteUrl: 'https://neon.tech' },
  { slug: 'supabase', name: 'Supabase', tagline: 'Open-source Firebase alternative', description: 'Complete backend platform with Postgres database, auth, storage, edge functions, and real-time subscriptions.', category: 'infra', tags: ['backend', 'auth', 'realtime'], websiteUrl: 'https://supabase.com' },
  { slug: 'railway', name: 'Railway', tagline: 'Deploy apps instantly from GitHub', description: 'Instant deployment platform with automatic CI/CD from GitHub. Managed databases, cron jobs, and private networking.', category: 'infra', tags: ['deployment', 'PaaS', 'instant'], websiteUrl: 'https://railway.app' },
  { slug: 'render', name: 'Render', tagline: 'Cloud application platform', description: 'Unified cloud to build and run apps. Web services, static sites, background workers, and managed databases.', category: 'infra', tags: ['deployment', 'PaaS', 'managed'], websiteUrl: 'https://render.com' },
  { slug: 'deno-deploy', name: 'Deno Deploy', tagline: 'Edge-first serverless platform', description: 'Deploy JavaScript and TypeScript globally at the edge. Built on Deno runtime with automatic HTTPS and zero config.', category: 'infra', tags: ['edge', 'Deno', 'serverless'], websiteUrl: 'https://deno.com/deploy' },
  { slug: 'helicone', name: 'Helicone', tagline: 'LLM observability and monitoring', description: 'One-line integration for LLM observability. Request logging, cost tracking, caching, and rate limiting for AI applications.', category: 'infra', tags: ['observability', 'LLM', 'logging'], websiteUrl: 'https://helicone.ai' },
  { slug: 'langsmith', name: 'LangSmith', tagline: 'LLM application debugging and monitoring', description: 'Debug, test, evaluate, and monitor LLM applications. Trace every step of your chain with detailed observability.', category: 'infra', tags: ['debugging', 'tracing', 'LangChain'], websiteUrl: 'https://smith.langchain.com' },
  { slug: 'wandb', name: 'Weights & Biases', tagline: 'ML experiment tracking and observability', description: 'Track experiments, visualize results, and collaborate on ML projects. Model registry, dataset versioning, and sweep optimization.', category: 'infra', tags: ['ML', 'experiments', 'tracking'], websiteUrl: 'https://wandb.ai' },
  { slug: 'portkey', name: 'Portkey', tagline: 'AI gateway with routing and guardrails', description: 'Production-ready AI gateway with automatic fallbacks, load balancing, caching, and content guardrails across 100+ LLMs.', category: 'infra', tags: ['gateway', 'routing', 'reliability'], websiteUrl: 'https://portkey.ai' },
  { slug: 'braintrust', name: 'BrainTrust', tagline: 'LLM evaluation and prompt management', description: 'End-to-end platform for evaluating, monitoring, and improving LLM applications. A/B testing, prompt versioning, and scoring.', category: 'infra', tags: ['evaluation', 'prompts', 'testing'], websiteUrl: 'https://braintrust.dev' },
  { slug: 'zep', name: 'Zep', tagline: 'Long-term memory for AI assistants', description: 'Persistent memory service for AI assistants. Automatic summarization, entity extraction, and temporal awareness.', category: 'infra', tags: ['memory', 'chat-history', 'context'], websiteUrl: 'https://getzep.com' },
  { slug: 'langtrace', name: 'Langtrace', tagline: 'Open-source observability for LLM apps', description: 'OpenTelemetry-based observability for LLM applications. Auto-instrumentation for major frameworks with trace visualization.', category: 'infra', tags: ['observability', 'open-source', 'tracing'], websiteUrl: 'https://langtrace.ai' },
  { slug: 'trigger-dev', name: 'Trigger.dev', tagline: 'Background job infrastructure for AI workflows', description: 'Run long-running AI tasks as background jobs. Retry logic, scheduling, and monitoring for agent workflows.', category: 'infra', tags: ['jobs', 'background', 'workflows'], websiteUrl: 'https://trigger.dev' },
  { slug: 'modal', name: 'Modal', tagline: 'Serverless GPU computing platform', description: 'Run GPU workloads without managing infrastructure. Instant cold starts, auto-scaling, and pay-per-second billing.', category: 'infra', tags: ['GPU', 'serverless', 'computing'], websiteUrl: 'https://modal.com' },
  { slug: 'fly-io', name: 'Fly.io', tagline: 'Edge application platform', description: 'Deploy apps globally at the edge with hardware-level isolation. Built-in Postgres, Redis, and volume storage.', category: 'infra', tags: ['edge', 'deployment', 'global'], websiteUrl: 'https://fly.io' },
  { slug: 'cloudflare-workers-ai', name: 'Cloudflare Workers AI', tagline: 'Edge AI inference platform', description: 'Run AI models at the edge on Cloudflare network. Serverless GPU inference with global distribution.', category: 'infra', tags: ['edge', 'AI', 'inference'], websiteUrl: 'https://developers.cloudflare.com/workers-ai' },
  { slug: 'inngest', name: 'Inngest', tagline: 'Event-driven background functions', description: 'Durable workflow engine for AI applications. Event-driven functions with step-level retries and fan-out concurrency.', category: 'infra', tags: ['events', 'workflows', 'durable'], websiteUrl: 'https://inngest.com' },
  { slug: 'upstash', name: 'Upstash', tagline: 'Serverless Redis and Kafka', description: 'Serverless data infrastructure with Redis, Kafka, and QStash. Pay-per-request pricing with global replication.', category: 'infra', tags: ['Redis', 'Kafka', 'serverless'], websiteUrl: 'https://upstash.com' },

  // ============================================================
  // Agent Platforms (10)
  // ============================================================
  { slug: 'openai-assistants', name: 'OpenAI Assistants', tagline: 'Managed agent runtime with tool use', description: 'Build AI assistants with tool use, code interpreter, and knowledge retrieval. Managed runtime with thread-based conversations.', category: 'platform', tags: ['agents', 'managed', 'OpenAI'], websiteUrl: 'https://platform.openai.com/docs/assistants' },
  { slug: 'claude-computer-use', name: 'Claude Computer Use', tagline: 'Browser and desktop automation by Claude', description: 'Claude can directly interact with computers through mouse clicks, keyboard input, and screen observation for end-to-end automation.', category: 'platform', tags: ['automation', 'browser', 'Anthropic'], websiteUrl: 'https://anthropic.com' },
  { slug: 'manus', name: 'Manus', tagline: 'Autonomous general-purpose AI agent', description: 'General-purpose autonomous agent that can browse the web, write code, and complete complex multi-step tasks.', category: 'platform', tags: ['autonomous', 'general', 'agent'], websiteUrl: 'https://manus.im' },
  { slug: 'devin-platform', name: 'Devin', tagline: 'Autonomous software engineering agent', description: 'Fully autonomous AI software engineer that can plan, code, test, and deploy. Handles complete development tasks end-to-end.', category: 'platform', tags: ['coding', 'autonomous', 'SWE'], websiteUrl: 'https://devin.ai' },
  { slug: 'cursor-platform', name: 'Cursor', tagline: 'AI-first code editor with agent mode', description: 'AI-powered code editor with inline completions, chat, and agent mode for multi-file editing. Built on VS Code.', category: 'platform', tags: ['coding', 'editor', 'agent'], websiteUrl: 'https://cursor.com' },
  { slug: 'windsurf', name: 'Windsurf', tagline: 'AI-powered IDE by Codeium', description: 'AI-native IDE with Cascade agent for multi-file editing, codebase understanding, and command-line integration.', category: 'platform', tags: ['coding', 'IDE', 'Codeium'], websiteUrl: 'https://codeium.com/windsurf' },
  { slug: 'replit-agent', name: 'Replit Agent', tagline: 'Build apps through conversation', description: 'Describe what you want and Replit Agent builds it. Full-stack app creation with automatic deployment and database setup.', category: 'platform', tags: ['coding', 'no-code', 'conversation'], websiteUrl: 'https://replit.com' },
  { slug: 'bolt-new', name: 'Bolt.new', tagline: 'AI full-stack app builder', description: 'Build and deploy full-stack web applications through AI conversation. Supports React, Next.js, and other frameworks.', category: 'platform', tags: ['full-stack', 'builder', 'web'], websiteUrl: 'https://bolt.new' },
  { slug: 'v0', name: 'v0', tagline: 'AI UI component generator by Vercel', description: 'Generate React UI components from text or image descriptions. Produces production-ready code with shadcn/ui components.', category: 'platform', tags: ['UI', 'components', 'Vercel'], websiteUrl: 'https://v0.dev' },
  { slug: 'lovable', name: 'Lovable', tagline: 'AI software engineer for full apps', description: 'Build complete applications with AI through iterative conversation. Full-stack generation with database, auth, and deployment.', category: 'platform', tags: ['full-stack', 'apps', 'AI'], websiteUrl: 'https://lovable.dev' },
];
